### ISSUE TITLE
After latest update:  druid.lua:186: attempt to index global 'Feral_Ability' (a nil value)

### ISSUE THREAD

**Issue by rbpaiett** [Vae2009/ConROC_Druid#2]
Message: Interface/AddOns/ConROC_Druid/druid.lua:186: attempt to index global 'Feral_Ability' (a nil value)
Time: Wed Dec 11 22:29:29 2024
Count: 3
Stack: Interface/AddOns/ConROC_Druid/druid.lua:186: attempt to index global 'Feral_Ability' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ConROC_Druid/druid.lua"]:186: in function `NextSpell'
[string "@Interface/AddOns/ConROC/core.lua"]:1090: in function `InvokeNextSpell'
[string "@Interface/AddOns/ConROC/buttons.lua"]:1875: in function `?'
[string "@Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:

**Comment by Vae2009** [comment]
Fixed
